name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-24.04

    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          config-file: .release-please-config.json

  release:
    name: Release
    needs: release-please
    if: needs.release-please.outputs.release_created
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build gem
        run: gem build demo-ga.gemspec

      - name: Push gem
        run: |
          mkdir -p ~/.gem
          echo "---" > ~/.gem/credentials
          echo ":github: Bearer ${{ secrets.GITHUB_TOKEN }}" >> ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          gem push demo-ga-*.gem --host "https://rubygems.pkg.github.com/labac-p"
          rm ~/.gem/credentials
