name: Release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      pull-requests: write

    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release Please
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          config-file:   .github/.release-please-config.json
          manifest-file: .github/.release-please-manifest.json

  release:
    name: Release
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    needs: release-please
    if: needs.release-please.outputs.release_created

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build gem
        run: gem build

      - name: Push gem
        run: |
          mkdir -p ~/.gem
          echo "---" > ~/.gem/credentials
          echo ":github: Bearer ${{ secrets.GITHUB_TOKEN }}" >> ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          gem push --key github --host "https://rubygems.pkg.github.com/labac-p" demo-ga-*.gem
